tiago_pro_configuration:
  arm_type_right:
    description: 'Arm type right'
    choices: ['tiago-pro', 'no-arm']
    default_value: 'tiago-pro'
  arm_type_left:
    description: 'Arm type left'
    choices: ['tiago-pro', 'no-arm']
    default_value: 'tiago-pro'
  wrist_model_right:
    description: 'Wrist model right'
    choices: ['spherical-wrist', 'wrist-2023']
    default_value: 'wrist-2023'
  wrist_model_left:
    description: 'Wrist model left'
    choices: ['spherical-wrist', 'wrist-2023']
    default_value: 'wrist-2023'
  laser_model:
    description: 'Base laser model'
    choices: ['no-laser', 'sick-571']
    default_value: 'sick-571'
  end_effector_right:
    description: 'End effector model right arm'
    choices: ['pal-pro-gripper', 'custom', 'no-end-effector']
    default_value: 'pal-pro-gripper'
  end_effector_left:
    description: 'End effector model left arm'
    choices: ['pal-pro-gripper', 'custom', 'no-end-effector']
    default_value: 'pal-pro-gripper'
  ft_sensor_right:
    description: 'FT sensor model right arm'
    choices: ['rokubi', 'no-ft-sensor']
    default_value: 'no-ft-sensor'
  ft_sensor_left:
    description: 'FT sensor model left arm'
    choices: ['rokubi', 'no-ft-sensor']
    default_value: 'no-ft-sensor'
  base_type:
    description: 'Base type'
    choices: ['omni_base']
    default_value: 'omni_base'
  camera_model:
    description: 'Head camera model'
    choices: ['realsense_d435']
    default_value: 'realsense_d435'