tiago_sea_dual_configuration:
  wheel_model:
    description: 'Wheel model'
    choices: ['nadia', 'moog']
    default_value: 'moog'
  arm_type_right:
    description: 'Arm type right'
    choices: ['sea', 'no-arm']
    default_value: 'sea'
  arm_type_left:
    description: 'Arm type left'
    choices: ['sea', 'no-arm']
    default_value: 'sea'
  laser_model:
    description: 'Base laser model'
    choices: ['no-laser', 'sick-571', 'sick-561', 'sick-551', 'hokuyo']
    default_value: 'sick-571'
  wrist_model_right:
    description: 'Wrist model right arm'
    choices: ['spherical-wrist']
    default_value: 'spherical-wrist'
  wrist_model_left:
    description: 'Wrist model left arm'
    choices: ['spherical-wrist']
    default_value: 'spherical-wrist'
  end_effector_right:
    description: 'End effector model right arm'
    choices: ['pal-pro-gripper', 'custom', 'no-end-effector']
    default_value: 'pal-pro-gripper'
  end_effector_left:
    description: 'End effector model left arm'
    choices: ['pal-pro-gripper','custom', 'no-end-effector']
    default_value: 'pal-pro-gripper'
  ft_sensor_right:
    description: 'FT sensor model right arm'
    choices: ['rokubi', 'no-ft-sensor']
    default_value: 'rokubi'
  ft_sensor_left:
    description: 'FT sensor model left arm'
    choices: ['rokubi', 'no-ft-sensor']
    default_value: 'rokubi'
  has_screen:
    description: 'Has screen at torso'
    choices: ['False', 'True']
    default_value: 'False'
  base_type:
    description: 'Base type'
    choices: ['pmb2', 'omni_base']
    default_value: 'pmb2'
  camera_model:
    description: 'Head camera model'
    choices: ['orbbec-astra', 'orbbec-astra-pro', 'asus-xtion', 'no-camera']
    default_value: 'orbbec-astra'
  has_velodyne:
    description: 'Has velodyne sensor'
    choices: ['False', 'True']
    default_value: 'False'
